[versions]
agp = "9.0.0"
kotlin = "2.3.0"
androidx-core = "1.17.0"
junit = "4.13.2"
androidx-junit = "1.3.0"
espresso-core = "3.7.0"
androidx-lifecycle = "2.10.0"
activity-compose = "1.12.2"
compose-bom = "2026.01.00"
ktor = "3.3.3"
koin = "4.2.0-beta3"
navigation3 = "1.0.0"
androidx-test-runner = "1.7.0"
androidx-test-core = "1.7.0"
exposed = "1.0.0-rc-4"
logbackClassic = "1.5.25"
postgresql = "42.7.9"
h2 = "2.4.240"
kotlinx-serialization = "1.9.0"
s3 = "1.5.122"
argon2 = "2.12"
datastore = "1.3.0-alpha04"
jwtdecode = "2.0.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
# lifecycle
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-navigation3 = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "androidx-lifecycle" }
# ktor common
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
# ktor client
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
# ktor service
ktor-network-tls = { module = "io.ktor:ktor-network-tls" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation" }
ktor-server-core = { module = "io.ktor:ktor-server-core" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors" }
ktor-server-di = { module = "io.ktor:ktor-server-di" }
ktor-server-host-common = { module = "io.ktor:ktor-server-host-common" }
ktor-server-sse = { module = "io.ktor:ktor-server-sse" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets" }
# ktor service test
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host" }
# koin
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-navigation3 = { module = "io.insert-koin:koin-compose-navigation3", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-androidx-startup = { module = "io.insert-koin:koin-androidx-startup", version.ref = "koin" }
# navigation3
androidx-navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "navigation3" }
androidx-navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "navigation3" }
# test
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidx-test-core" }
# exposed
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-crypt = { module = "org.jetbrains.exposed:exposed-crypt", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-json = { module = "org.jetbrains.exposed:exposed-json", version.ref = "exposed" }
exposed-money = { module = "org.jetbrains.exposed:exposed-money", version.ref = "exposed" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
# log
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logbackClassic" }
# database
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
# serialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
# datastore
datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
# other
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
s3 = { module = "aws.sdk.kotlin:s3", version.ref = "s3" }
argon2-jvm = { module = "de.mkammerer:argon2-jvm", version.ref = "argon2" }
jwtdecode = { group = "com.auth0.android", name = "jwtdecode", version.ref = "jwtdecode" }

[bundles]
ktor-client = [
    "ktor-client-cio",
    "ktor-client-core",
    "ktor-client-content-negotiation",
    "ktor-client-logging",
    "ktor-client-websockets",
    "ktor-serialization-kotlinx-json",
]
ktor-server = [
    "ktor-network-tls",
    "ktor-server-auth",
    "ktor-server-auth-jwt",
    "ktor-server-call-logging",
    "ktor-server-cio",
    "ktor-server-config-yaml",
    "ktor-server-content-negotiation",
    "ktor-server-core",
    "ktor-server-cors",
    "ktor-server-di",
    "ktor-server-host-common",
    "ktor-server-sse",
    "ktor-server-status-pages",
    "ktor-server-websockets",
    "ktor-serialization-kotlinx-json",
]
exposed = [
    "exposed-core",
    "exposed-crypt",
    "exposed-jdbc",
    "exposed-dao",
    "exposed-json",
    "exposed-money",
    "exposed-kotlin-datetime",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
